// Author: Chris Aragao
// Date: 8.31.2022
// Purpose: Documentation for Power Query on cirt.txt file
// Notes: Filepath is just a placeholder for the file path for the text field

// CHANGELOG
//----------------
// 8.31.2022: Initial documentation provided.

(FILEPATH as text)=>

let
    Source = Csv.Document(File.Contents(FILEPATH & "cirt.txt"),[Delimiter="	", Columns=89, Encoding=1252, QuoteStyle=QuoteStyle.None]),
        #"Renamed Columns" = Table.RenameColumns(Source,{{"Column1", "mccase"}, {"Column2", "unit"}, {"Column3", "last_update"}, {"Column4", "vessel_ind"}, {"Column5", "personnel_ind"}, {"Column6", "facility_ind"}, {"Column7", "pollution_ind"}, {"Column8", "incident_date"}, {"Column9", "incident_time"}, {"Column10", "incident_date_known"}, {"Column11", "ref_case"}, {"Column12", "notify_dt"}, {"Column13", "notify_time"}, {"Column14", "reporter_type"}, {"Column15", "subject"}, {"Column16", "location"}, {"Column17", "stat_verify"}, {"Column18", "stat_not_verify"}, {"Column19", "verify_not_report"}, {"Column20", "ctf_ind"}, {"Column21", "invest_date"}, {"Column22", "command_endorse"}, {"Column23", "command_closed"}, {"Column24", "command_date"}, {"Column25", "dist_req"}, {"Column26", "dist_endorse"}, {"Column27", "dist_cls"}, {"Column28", "dist_dt"}, {"Column29", "hq_req"}, {"Column30", "hq_endorse"}, {"Column31", "hq_dt"}, {"Column32", "city"}, {"Column33", "state"}, {"Column34", "waterbody"}, {"Column35", "river_mile"}, {"Column36", "river_tenths"}, {"Column40", "casualty_class"}, {"Column41", "sign_marine_ind"}, {"Column42", "deaths"}, {"Column43", "missing"}, {"Column44", "injured"}, {"Column45", "total_damage"}, {"Column39", "pri_nature"}, {"Column46", "mode"}, {"Column47", "severity"}, {"Column48", "material_category"}, {"Column49", "on_scene_coordinator"}, {"Column50", "epa_region"}, {"Column51", "epa_response_req"}, {"Column52", "nrc_case"}, {"Column53", "district"}, {"Column54", "case_control_level"}, {"Column55", "mcpd"}, {"Column56", "mcns"}, {"Column57", "mcpa"}, {"Column58", "mcts"}, {"Column59", "mcpi"}, {"Column60", "mccr"}, {"Column61", "mcsi"}, {"Column62", "mcdd"}, {"Column63", "mcdr"}, {"Column64", "mccg"}, {"Column65", "mcfc"}, {"Column66", "mcfe"}, {"Column67", "mscf"}, {"Column68", "mchm"}, {"Column69", "mcpc"}, {"Column70", "mchf"}, {"Column71", "nrc_ind"}, {"Column72", "publ_vsl_ind"}, {"Column73", "boating_ind"}, {"Column74", "num_vsl"}, {"Column75", "num_fac"}, {"Column76", "mcls"}, {"Column77", "mcwx"}, {"Column78", "rec_end_ind"}, {"Column79", "supp_comp"}, {"Column80", "fwcpa"}, {"Column81", "fwcpa_amt"}, {"Column82", "cercla"}, {"Column83", "cercla_amt"}, {"Column84", "nfs_ind"}, {"Column85", "mcpd_closed"}, {"Column86", "human_fac_num"}, {"Column87", "fy"}, {"Column88", "closed_by"}, {"Column89", "sp"}}),
    #"Replaced Y with 1" = Table.ReplaceValue(#"Renamed Columns","Y","1",Replacer.ReplaceValue,{"mccase", "unit", "last_update", "vessel_ind", "personnel_ind", "facility_ind", "pollution_ind", "incident_date", "incident_time", "incident_date_known", "ref_case", "notify_dt", "notify_time", "reporter_type", "subject", "location", "stat_verify", "stat_not_verify", "verify_not_report", "ctf_ind", "invest_date", "command_endorse", "command_closed", "command_date", "dist_req", "dist_endorse", "dist_cls", "dist_dt", "hq_req", "hq_endorse", "hq_dt", "city", "state", "waterbody", "river_mile", "river_tenths", "Column37", "Column38", "pri_nature", "casualty_class", "sign_marine_ind", "deaths", "missing", "injured", "total_damage", "mode", "severity", "material_category", "on_scene_coordinator", "epa_region", "epa_response_req", "nrc_case", "district", "case_control_level", "mcpd", "mcns", "mcpa", "mcts", "mcpi", "mccr", "mcsi", "mcdd", "mcdr", "mccg", "mcfc", "mcfe", "mscf", "mchm", "mcpc", "mchf", "nrc_ind", "publ_vsl_ind", "boating_ind", "num_vsl", "num_fac", "mcls", "mcwx", "rec_end_ind", "supp_comp", "fwcpa", "fwcpa_amt", "cercla", "cercla_amt", "nfs_ind", "mcpd_closed", "human_fac_num", "fy", "closed_by", "sp"}),
    #"Replaced N with 0" = Table.ReplaceValue(#"Replaced Y with 1","N","0",Replacer.ReplaceValue,{"mccase", "unit", "last_update", "vessel_ind", "personnel_ind", "facility_ind", "pollution_ind", "incident_date", "incident_time", "incident_date_known", "ref_case", "notify_dt", "notify_time", "reporter_type", "subject", "location", "stat_verify", "stat_not_verify", "verify_not_report", "ctf_ind", "invest_date", "command_endorse", "command_closed", "command_date", "dist_req", "dist_endorse", "dist_cls", "dist_dt", "hq_req", "hq_endorse", "hq_dt", "city", "state", "waterbody", "river_mile", "river_tenths", "Column37", "Column38", "pri_nature", "casualty_class", "sign_marine_ind", "deaths", "missing", "injured", "total_damage", "mode", "severity", "material_category", "on_scene_coordinator", "epa_region", "epa_response_req", "nrc_case", "district", "case_control_level", "mcpd", "mcns", "mcpa", "mcts", "mcpi", "mccr", "mcsi", "mcdd", "mcdr", "mccg", "mcfc", "mcfe", "mscf", "mchm", "mcpc", "mchf", "nrc_ind", "publ_vsl_ind", "boating_ind", "num_vsl", "num_fac", "mcls", "mcwx", "rec_end_ind", "supp_comp", "fwcpa", "fwcpa_amt", "cercla", "cercla_amt", "nfs_ind", "mcpd_closed", "human_fac_num", "fy", "closed_by", "sp"}),
    #"Replaced X with 1" = Table.ReplaceValue(#"Replaced N with 0","X","1",Replacer.ReplaceValue,{"mccase", "unit", "last_update", "vessel_ind", "personnel_ind", "facility_ind", "pollution_ind", "incident_date", "incident_time", "incident_date_known", "ref_case", "notify_dt", "notify_time", "reporter_type", "subject", "location", "stat_verify", "stat_not_verify", "verify_not_report", "ctf_ind", "invest_date", "command_endorse", "command_closed", "command_date", "dist_req", "dist_endorse", "dist_cls", "dist_dt", "hq_req", "hq_endorse", "hq_dt", "city", "state", "waterbody", "river_mile", "river_tenths", "Column37", "Column38", "pri_nature", "casualty_class", "sign_marine_ind", "deaths", "missing", "injured", "total_damage", "mode", "severity", "material_category", "on_scene_coordinator", "epa_region", "epa_response_req", "nrc_case", "district", "case_control_level", "mcpd", "mcns", "mcpa", "mcts", "mcpi", "mccr", "mcsi", "mcdd", "mcdr", "mccg", "mcfc", "mcfe", "mscf", "mchm", "mcpc", "mchf", "nrc_ind", "publ_vsl_ind", "boating_ind", "num_vsl", "num_fac", "mcls", "mcwx", "rec_end_ind", "supp_comp", "fwcpa", "fwcpa_amt", "cercla", "cercla_amt", "nfs_ind", "mcpd_closed", "human_fac_num", "fy", "closed_by", "sp"}),
    #"Replaced O with 0" = Table.ReplaceValue(#"Replaced X with 1","O","0",Replacer.ReplaceText,{"sign_marine_ind", "boating_ind"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Replaced O with 0",{{"last_update", type date}, {"vessel_ind", Int64.Type}, {"personnel_ind", Int64.Type}, {"facility_ind", Int64.Type}, {"pollution_ind", Int64.Type}, {"incident_date", type date}, {"notify_dt", type date}, {"stat_not_verify", Int64.Type}, {"stat_verify", Int64.Type}, {"verify_not_report", Int64.Type}, {"ctf_ind", Int64.Type}, {"command_endorse", Int64.Type}, {"command_closed", Int64.Type}, {"invest_date", type date}, {"command_date", type date}, {"dist_endorse", Int64.Type}, {"dist_req", Int64.Type}, {"dist_cls", Int64.Type}, {"dist_dt", type date}, {"hq_endorse", Int64.Type}, {"hq_req", Int64.Type}, {"hq_dt", type date}, {"river_mile", Int64.Type}, {"river_tenths", Int64.Type}, {"sign_marine_ind", Int64.Type}, {"deaths", Int64.Type}, {"missing", Int64.Type}, {"injured", Int64.Type}, {"total_damage", type number}, {"epa_region", Int64.Type}, {"epa_response_req", Int64.Type}, {"mcpd", Int64.Type}, {"mcns", Int64.Type}, {"mcpa", Int64.Type}, {"mcts", Int64.Type}, {"mcpi", Int64.Type}, {"mccr", Int64.Type}, {"mcsi", Int64.Type}, {"mcdd", Int64.Type}, {"mcdr", Int64.Type}, {"mccg", Int64.Type}, {"mcfc", Int64.Type}, {"mcfe", Int64.Type}, {"mscf", Int64.Type}, {"mchm", Int64.Type}, {"mcpc", Int64.Type}, {"mchf", Int64.Type}, {"nrc_ind", Int64.Type},  {"boating_ind", Int64.Type}, {"num_vsl", Int64.Type}, {"num_fac", Int64.Type}, {"mcls", Int64.Type}, {"mcwx", Int64.Type}, {"rec_end_ind", Int64.Type}, {"supp_comp", Int64.Type}, {"fwcpa_amt", type number}, {"cercla_amt", type number}, {"nfs_ind", Int64.Type}, {"human_fac_num", Int64.Type}}),
    #"Remove Spaces from Lat and Long" = Table.ReplaceValue(#"Changed Type"," ","",Replacer.ReplaceText,{"Column37", "Column38"}),
    #"Split latitude" = Table.SplitColumn(#"Remove Spaces from Lat and Long", "Column37", Splitter.SplitTextByPositions({0, 1}), {"Column37.1", "Column37.2"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Split latitude",{{"mccase", type text}, {"unit", type text}, {"incident_time", Int64.Type}, {"ref_case", type text}, {"notify_time", Int64.Type}, {"reporter_type", type text}, {"subject", type text}, {"location", type text}, {"city", type text}, {"state", type text}, {"waterbody", type text}, {"Column37.1", type text}, {"Column37.2", Int64.Type}, {"Column38", type text}, {"pri_nature", type text}, {"casualty_class", type text}, {"mode", type text}, {"severity", type text}, {"material_category", type text}, {"on_scene_coordinator", type text}, {"nrc_case", type text}, {"district", type text}, {"case_control_level", type text}, {"fwcpa", type text}, {"mcpd_closed", type text}, {"fy", Int64.Type}, {"closed_by", type text}, {"sp", type text}}),
    #"Split longitude" = Table.SplitColumn(#"Changed Type1", "Column38", Splitter.SplitTextByPositions({0, 1}), {"Column38.1", "Column38.2"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Split longitude",{{"Column38.1", type text}, {"Column38.2", Int64.Type}}),
    #"Calc latitude" = Table.AddColumn(#"Changed Type2", "latitude", each fnConvertLatLong([Column37.2], 0.001, [Column37.1])),
    #"Calc longitude" = Table.AddColumn(#"Calc latitude", "longitude", each fnConvertLatLong([Column38.2], 0.001, [Column38.1])),
    #"Removed Other Columns" = Table.SelectColumns(#"Calc longitude",{"mccase", "unit", "last_update", "vessel_ind", "personnel_ind", "facility_ind", "pollution_ind", "incident_date", "incident_time", "incident_date_known", "ref_case", "notify_dt", "notify_time", "reporter_type", "subject", "location", "stat_verify", "stat_not_verify", "verify_not_report", "ctf_ind", "invest_date", "command_endorse", "command_closed", "command_date", "dist_req", "dist_endorse", "dist_cls", "dist_dt", "hq_req", "hq_endorse", "hq_dt", "city", "state", "waterbody", "river_mile", "river_tenths", "pri_nature", "casualty_class", "sign_marine_ind", "deaths", "missing", "injured", "total_damage", "mode", "severity", "material_category", "on_scene_coordinator", "epa_region", "epa_response_req", "nrc_case", "district", "case_control_level", "mcpd", "mcns", "mcpa", "mcts", "mcpi", "mccr", "mcsi", "mcdd", "mcdr", "mccg", "mcfc", "mcfe", "mscf", "mchm", "mcpc", "mchf", "nrc_ind", "publ_vsl_ind", "boating_ind", "num_vsl", "num_fac", "mcls", "mcwx", "rec_end_ind", "supp_comp", "fwcpa", "fwcpa_amt", "cercla", "cercla_amt", "nfs_ind", "mcpd_closed", "human_fac_num", "fy", "closed_by", "sp", "latitude", "longitude"}),
    #"Replaced NS with NO SPILL" = Table.ReplaceValue(#"Removed Other Columns","NS","NO SPILL",Replacer.ReplaceValue,{"severity"})
in
    #"Replaced NS with NO SPILL"