// Author: Chris Aragao
// Date: 9.2.2022
// Purpose: Documentation for Power Query on cwxt_pre.txt file
// Notes: Filepath is just a placeholder for the file path for the text field

// CHANGELOG
//----------------
// 9.2.2022: Initial documentation provided.


(FILEPATH as text)=>

let
    Source = Csv.Document(File.Contents(FILEPATH & "cwxt.txt"),[Delimiter="	", Columns=70, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", Int64.Type}, {"Column6", type text}, {"Column7", type text}, {"Column8", Int64.Type}, {"Column9", Int64.Type}, {"Column10", Int64.Type}, {"Column11", type text}, {"Column12", Int64.Type}, {"Column13", Int64.Type}, {"Column14", type text}, {"Column15", Int64.Type}, {"Column16", Int64.Type}, {"Column17", type text}, {"Column18", Int64.Type}, {"Column19", Int64.Type}, {"Column20", type text}, {"Column21", type text}, {"Column22", type text}, {"Column23", type text}, {"Column24", type text}, {"Column25", type text}, {"Column26", type text}, {"Column27", type text}, {"Column28", type text}, {"Column29", type text}, {"Column30", Int64.Type}, {"Column31", type text}, {"Column32", type text}, {"Column33", type text}, {"Column34", Int64.Type}, {"Column35", type text}, {"Column36", Int64.Type}, {"Column37", type text}, {"Column38", Int64.Type}, {"Column39", type text}, {"Column40", Int64.Type}, {"Column41", type text}, {"Column42", Int64.Type}, {"Column43", type text}, {"Column44", Int64.Type}, {"Column45", type text}, {"Column46", type text}, {"Column47", Int64.Type}, {"Column48", type text}, {"Column49", type text}, {"Column50", Int64.Type}, {"Column51", type text}, {"Column52", type text}, {"Column53", Int64.Type}, {"Column54", type text}, {"Column55", type text}, {"Column56", type text}, {"Column57", type text}, {"Column58", type text}, {"Column59", type text}, {"Column60", type text}, {"Column61", type text}, {"Column62", type text}, {"Column63", type text}, {"Column64", type text}, {"Column65", type text}, {"Column66", type text}, {"Column67", type text}, {"Column68", type text}, {"Column69", type text}, {"Column70", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "mccase"}, {"Column2", "pre_time"}, {"Column3", "pre_weather"}, {"Column4", "pre_vis_condition"}, {"Column5", "pre_vis_dist"}, {"Column6", "pre_vis_dis_units"}, {"Column7", "pre_ex_other"}, {"Column8", "pre_air_temp"}, {"Column9", "pre_wind_spe"}, {"Column10", "pre_wind_dir"}, {"Column11", "pre_wind_dir_units"}, {"Column12", "pre_wave_hts"}, {"Column13", "pre_wave_dir"}, {"Column14", "pre_wave_dir_units"}, {"Column15", "pre_swell_hts"}, {"Column16", "pre_well_dir"}, {"Column17", "pre_swell_dir_units"}, {"Column18", "pre_crnt_spe"}, {"Column19", "pre_crnt_dir"}, {"Column20", "pre_crnt_dir_units"}, {"Column21", "pre_river_stage"}, {"Column22", "pre_tide"}, {"Column23", "post_wx_sig"}, {"Column24", "post_wx"}, {"Column25", "post_wx_trend"}, {"Column26", "post_vis_con_sig"}, {"Column27", "post_vis_con"}, {"Column28", "post_vis_con_trend"}, {"Column29", "post_vis_dis_sig"}, {"Column30", "post_vis_dis"}, {"Column31", "post_vis_dis_units"}, {"Column32", "post_vis_dis_trend"}, {"Column33", "post_air_temp_sig"}, {"Column34", "post_air_temp"}, {"Column35", "post_air_temp_trend"}, {"Column36", "post_wind_spe"}, {"Column37", "post_wind_spe_trend"}, {"Column38", "post_wave_hts"}, {"Column39", "post_wave_hts_trend"}, {"Column40", "post_swell_hts"}, {"Column41", "post_swell_hts_trend"}, {"Column42", "post_crnt_spe"}, {"Column43", "post_crnt_spe_trend"}, {"Column44", "post_wind_dir"}, {"Column45", "post_wind_dir_units"}, {"Column46", "post_wind_dir_trend"}, {"Column47", "post_wave_dir"}, {"Column48", "post_wave_dir_units"}, {"Column49", "post_wave_dir_trend"}, {"Column50", "post_swell_dir"}, {"Column51", "post_swell_dir_inits"}, {"Column52", "post_swell_dir_trend"}, {"Column53", "post_crnt_dir"}, {"Column54", "post_crnt_dir_units"}, {"Column55", "post_crnt_dir_trend"}, {"Column56", "post_river_stage"}, {"Column57", "post_river_stage_trend"}, {"Column58", "post_tide"}, {"Column59", "post_tide_trend"}, {"Column60", "post_wind_spe_sig"}, {"Column61", "post_wave_hts_sig"}, {"Column62", "post_swell_hts_sig"}, {"Column63", "post_crnt_spe_sig"}, {"Column64", "post_wind_dir_sig"}, {"Column65", "post_wave_dir_sig"}, {"Column66", "post_swell_dir_sig"}, {"Column67", "post_crnt_dir_sig"}, {"Column68", "post_river_stage_sig"}, {"Column69", "post_tide_sig"}, {"Column70", "sp"}}),
    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns",{"mccase", "pre_time", "pre_weather", "pre_vis_condition", "pre_vis_dist", "pre_vis_dis_units", "pre_ex_other", "pre_air_temp", "pre_wind_spe", "pre_wind_dir", "pre_wind_dir_units", "pre_wave_hts", "pre_wave_dir", "pre_wave_dir_units", "pre_swell_hts", "pre_well_dir", "pre_swell_dir_units", "pre_crnt_spe", "pre_crnt_dir", "pre_crnt_dir_units", "pre_river_stage", "pre_tide", "sp"})
in
    #"Removed Other Columns"