// Author: Chris Aragao
// Date: 9.3.2022
// Purpose: Documentation for Power Query on vidt.txt file. ]
//          This file was normalized a little (6 separate tables).
//          Vessel; Measurements; Indicators; Types; Dates; Places          
// Notes: Filepath is just a placeholder for the file path for the text field

// CHANGELOG
//----------------
// 9.3.2022: Initial documentation provided.

(FILEPATH as text)=>

let
    Source = Csv.Document(File.Contents(FILEPATH & "vidt.txt"),[Delimiter="	", Columns=97, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type date}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", Int64.Type}, {"Column20", type text}, {"Column21", type text}, {"Column22", Int64.Type}, {"Column23", type date}, {"Column24", type text}, {"Column25", type date}, {"Column26", type text}, {"Column27", Int64.Type}, {"Column28", Int64.Type}, {"Column29", Int64.Type}, {"Column30", Int64.Type}, {"Column31", Int64.Type}, {"Column32", type text}, {"Column33", type text}, {"Column34", type text}, {"Column35", Int64.Type}, {"Column36", type text}, {"Column37", type text}, {"Column38", type date}, {"Column39", type text}, {"Column40", Int64.Type}, {"Column41", type text}, {"Column42", type text}, {"Column43", Int64.Type}, {"Column44", type text}, {"Column45", type text}, {"Column46", type date}, {"Column47", type date}, {"Column48", type date}, {"Column49", type text}, {"Column50", type text}, {"Column51", type text}, {"Column52", type text}, {"Column53", type text}, {"Column54", type text}, {"Column55", type text}, {"Column56", Int64.Type}, {"Column57", Int64.Type}, {"Column58", type text}, {"Column59", Int64.Type}, {"Column60", Int64.Type}, {"Column61", type text}, {"Column62", type number}, {"Column63", type number}, {"Column64", type number}, {"Column65", type number}, {"Column66", type number}, {"Column67", type number}, {"Column68", type number}, {"Column69", Int64.Type}, {"Column70", type text}, {"Column71", type text}, {"Column72", type text}, {"Column73", type text}, {"Column74", type text}, {"Column75", type text}, {"Column76", type text}, {"Column77", type text}, {"Column78", type text}, {"Column79", type text}, {"Column80", type text}, {"Column81", type text}, {"Column82", type text}, {"Column83", type text}, {"Column84", type text}, {"Column85", type text}, {"Column86", type text}, {"Column87", type text}, {"Column88", type text}, {"Column89", type text}, {"Column90", type text}, {"Column91", type text}, {"Column92", type text}, {"Column93", type text}, {"Column94", type text}, {"Column95", type text}, {"Column96", type text}, {"Column97", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "vessel_key"}, {"Column2", "port_of_certification"}, {"Column3", "home_port"}, {"Column4", "vessel_name"}, {"Column5", "primary_vessel_id"}, {"Column6", "call_sign"}, {"Column7", "flag"}, {"Column8", "vin1"}, {"Column9", "vin2"}, {"Column10", "vin3"}, {"Column11", "vin4"}, {"Column12", "design_type"}, {"Column13", "service"}, {"Column14", "inspect_cert_date"}, {"Column15", "cod_indicator"}, {"Column16", "inspection_concern"}, {"Column17", "port_safety_concern"}, {"Column18", "vessel_archive_indicator"}, {"Column19", "imo_number"}, {"Column20", "inspection_subchapter"}, {"Column21", "vessel_use"}, {"Column22", "deadweight_tons"}, {"Column23", "build_date"}, {"Column24", "build_place"}, {"Column25", "date_keel_laid"}, {"Column26", "operating_route"}, {"Column27", "minimum_crew"}, {"Column28", "number_of_passengers"}, {"Column29", "max_passengers_allowed"}, {"Column30", "max_other_crew_allowed"}, {"Column31", "ppl_add_to_crew"}, {"Column32", "stability_doc_status"}, {"Column33", "cargo_authority"}, {"Column34", "highest_cargo_grade"}, {"Column35", "total_capacity"}, {"Column36", "stability_letter_ind"}, {"Column37", "stability_book_ind"}, {"Column38", "stability_approval_date"}, {"Column39", "stability_port"}, {"Column40", "cfr_for_load_line"}, {"Column41", "vessel_load_line_type"}, {"Column42", "route_type_load_line"}, {"Column43", "freeboard_used_load_line"}, {"Column44", "hazbulk_ind"}, {"Column45", "deck_drain_class"}, {"Column46", "contract_date"}, {"Column47", "delivery_date"}, {"Column48", "init_cert_date"}, {"Column49", "build_year"}, {"Column50", "capacity_units"}, {"Column51", "plan_review_office"}, {"Column52", "yard_built"}, {"Column53", "hull_humber"}, {"Column54", "build_country"}, {"Column55", "calculation_method"}, {"Column56", "gross_tons"}, {"Column57", "itc_gross_tons"}, {"Column58", "dual_gross_tons"}, {"Column59", "net_tons"}, {"Column60", "itc_net_tons"}, {"Column61", "dual_net_tons"}, {"Column62", "us_length"}, {"Column63", "us_breadth"}, {"Column64", "us_depth"}, {"Column65", "itc_length"}, {"Column66", "itc_breadth"}, {"Column67", "itc_depth"}, {"Column68", "overall_length"}, {"Column69", "displacement_tons"}, {"Column70", "itc_ton_ind"}, {"Column71", "vessel_type"}, {"Column72", "hull_material"}, {"Column73", "self_propelled_ind"}, {"Column74", "coastwise_trade"}, {"Column75", "great_lakes_trade"}, {"Column76", "fisheries_trade"}, {"Column77", "coastwise_bowater_only"}, {"Column78", "registry"}, {"Column79", "recreation"}, {"Column80", "rest_cw"}, {"Column81", "rest_fish"}, {"Column82", "rest_reg"}, {"Column83", "rest_rec"}, {"Column84", "rest_gl"}, {"Column85", "spec_leg_coastwise"}, {"Column86", "captured_vessel"}, {"Column87", "special_leg_fishery"}, {"Column88", "forfeited_vessel"}, {"Column89", "spec_leg_call_home_port"}, {"Column90", "wrecked_vessel"}, {"Column91", "no_entitlements"}, {"Column92", "us_service_ind"}, {"Column93", "cod_status"}, {"Column94", "double_side_type"}, {"Column95", "double_bottom_type"}, {"Column96", "propulsion_type"}, {"Column97", "sp"}}),
    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns",{"vessel_key", "port_of_certification", "home_port", "flag", "build_place", "yard_built", "build_country"})
in
    #"Removed Other Columns"